development: &default
  adapter: postgresql
  encoding: unicode
  database: hound
  username: fb_hound
  password: <%= ENV.fetch('DB_PASSWORD') %>
  host: <%= ENV.fetch('DB_HOST') %>
  port: <%= ENV.fetch('DB_PORT') %>
  reconnect: true

test:
  <<: *default
  database: hound_test
